name: Run Deployment Managment Groups
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az account show
          az group list

      - name: 'Run managment group commands'
        run: |
              dateYMD=$(date +%Y%m%dT%H%M%S%NZ)
              NAME="alz-MGDeployment-${dateYMD}"
              LOCATION="eastus"
              TEMPLATEFILE="https://github.com/jacobrhouse/ALZ-Bicep-001infra-as-code/bicep/modules/managementGroups/managementGroups.bicep"
              PARAMETERS="@infra-as-code/bicep/modules/managementGroups/parameters/managementGroups.parameters.all.json"

              az deployment tenant create --name ${NAME:0:63} --location $LOCATION --template-file $TEMPLATEFILE --parameters $PARAMETERS
